export {Layout} from './layout'
export {CadastroPeca} from './cadastros'
export {CadastroEstoque} from './cadastros'
export {CadastroLocacao} from './cadastros'
export {AlteracaoEstoque} from './alteracoes'
export {SaidaPeca} from './lancamentos'
export {Login} from './login'
export {ProtectedRoute} from './protecaoRota'