export {usePecaService} from './peca.service'
export {useLocacaoService} from './locacao.service'
export {useEstoqueService} from './estoque.service'
export {useChassisService} from './chassis.service'
export {useEstapaService} from './estapa.service'
export {useSessaoService} from './sessao.service'